<div class="nbd-gallery-con">
    <div class="nbd-sidebar">
        <?php include_once('sidebar.phtml'); ?>
    </div>
</div>
<script>
    var is_nbd_gallery = 1;
</script> 
<style>       
    .nbd-gallery header h1{
        background-image: url('<?php echo $this->getViewFileUrl('Netbaseteam_Onlinedesign::images/gallery.jpg') ?>');
    }
    .onlinedesign-template-index span.nbd-gallery-item-name {
        float: left;
    }
    .onlinedesign-template-index a.nbd-popup-start-design:hover {
        color: white;
    }
    .onlinedesign-template-index .nbd-like-icons {
        float: right;
    }
</style>