<div style="width: 1px; height: 30px;"></div>
<div class="toolbar-common">
    <ul class="nbd-main-menu">
        <?php do_action('nbd_modern_before_layer_common_menu'); ?>
        <li ng-if="settings.is_mobile" class="menu-item item-opacity ipad-mini-hidden" ng-click="copyLayers()">
            <i class="icon-nbd icon-nbd-content-copy nbd-tooltip-hover" title="<?php echo __('Duplicate'); ?>"></i>
        </li>        
        <li ng-if="settings.is_mobile" class="menu-item item-opacity ipad-mini-hidden" ng-click="deleteLayers()">
            <i class="icon-nbd icon-nbd-delete nbd-tooltip-hover" title="<?php echo __('Delete'); ?>"></i>
        </li> 
        <?php if( is_user_logged_in() ): ?>
        <li ng-if="false" class="menu-item item-opacity" ng-click="storeLayers()">
            <i style="height: 24px;" class="icon-nbd nbd-tooltip-hover" title="<?php echo __('Store layers as your own design'); ?>">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M0 0h24v24H0z" fill="none"/><path fill="#888" d="M17 3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V7l-4-4zm-5 16c-1.66 0-3-1.34-3-3s1.34-3 3-3 3 1.34 3 3-1.34 3-3 3zm3-10H5V5h10v4z"/></svg>
            </i>
        </li>
        <?php endif; ?>
        <li class="menu-item item-opacity ipad-mini-hidden" data-range="true" ng-show="stages[currentStage].states.enableRotate">
            <i class="icon-nbd icon-nbd-refresh nbd-tooltip-hover" title="<?php echo __('Angle'); ?>"></i>
            <div class="sub-menu" data-pos="center">
                <div class="main-ranges" style="padding: 30px 15px 10px;">
                    <div class="range range-opacity">
                        <label><?php echo __('Angle'); ?></label>
                        <div class="main-track">
                            <input class="slide-input" type="range" step="1" min="0" max="360" ng-change="setLayerAttribute('angle', stages[currentStage].states.angle)" ng-model="stages[currentStage].states.angle">
                            <span class="range-track"></span>
                        </div>
                        <span class="value-display">{{stages[currentStage].states.angle}}</span>
                    </div>
                </div>
            </div>
        </li>
        <li class="menu-item item-opacity" data-range="true" ng-show="stages[currentStage].states.enableOpacity">
            <i class="icon-nbd icon-nbd-opacity nbd-tooltip-hover" title="<?php echo __('Opacity'); ?>"></i>
            <div class="sub-menu" data-pos="center">
                <div class="main-ranges" style="padding: 30px 15px 10px;">
                    <div class="range range-opacity">
                        <label><?php echo __('Opacity'); ?></label>
                        <div class="main-track">
                            <input class="slide-input" type="range" step="1" min="0" max="100" ng-change="setTextAttribute('opacity', stages[currentStage].states.opacity / 100)" ng-model="stages[currentStage].states.opacity">
                            <span class="range-track"></span>
                        </div>
                        <span class="value-display">{{stages[currentStage].states.opacity}}</span>
                    </div>
                </div>
            </div>
        </li>
        <li class="menu-item item-stack ipad-mini-hidden" ng-class="stages[currentStage].states.isLayer ? '' : 'nbd-disabled'">
            <i class="icon-nbd icon-nbd-layer-stack nbd-tooltip-hover" title="<?php echo __('Layer stack'); ?>"></i>
            <div class="sub-menu" data-pos="right">
                <ul>
                    <li class="sub-menu-item" ng-click="setStackPosition('bring-front')">
                        <i class="icon-nbd icon-nbd-bring-to-front"></i>
                        <span><?php echo __('Bring to Front'); ?></span>
                        <span class="keyboard">{{ 'M-S-]' | keyboardShortcut }}</span>
                    </li>
                    <li class="sub-menu-item" ng-click="setStackPosition('bring-forward')">
                        <i class="icon-nbd icon-nbd-bring-forward"></i>
                        <span><?php echo __('Bring Forward'); ?></span>
                        <span class="keyboard">{{ 'M-]' | keyboardShortcut }}</span>
                    </li>
                    <li class="sub-menu-item" ng-click="setStackPosition('send-backward')">
                        <i class="icon-nbd icon-nbd-sent-to-backward"></i>
                        <span><?php echo __('Send to Backward'); ?></span>
                        <span class="keyboard">{{ 'M-[' | keyboardShortcut }}</span>
                    </li>
                    <li class="sub-menu-item" ng-click="setStackPosition('send-back')">
                        <i class="icon-nbd icon-nbd-send-to-back"></i>
                        <span><?php echo __('Send to Back'); ?></span>
                        <span class="keyboard">{{ 'M-S-[' | keyboardShortcut }}</span>
                    </li>
                </ul>
            </div>
        </li>
        <li class="menu-item item-position">
            <i class="icon-nbd icon-nbd-baseline-tune nbd-tooltip-hover" title="<?php echo __('layer position'); ?>"></i>
            <div class="sub-menu" data-pos="right">
                <ul>
                    <i class="icon-nbd-clear nbd-close-sub-menu"></i>
                    <li class="title">
                        <span>Layer position</span>
                        <i class="colse"></i>
                    </li>
                    <li ng-click="translateLayer('vertical')"><i class="icon-nbd icon-nbd-fomat-vertical-align-center nbd-tooltip-hover" title="<?php echo __('Center horizontal'); ?>"></i></li>
                    <li ng-click="translateLayer('top-left')"><i class="icon-nbd icon-nbd-fomat-top-left nbd-tooltip-hover rotate-90" title="<?php echo __('Top left'); ?>"></i></li>
                    <li ng-click="translateLayer('top-center')"><i class="icon-nbd icon-nbd-fomat-top-left nbd-tooltip-hover rotate-45" title="<?php echo __('Top center'); ?>"></i></li>
                    <li ng-click="translateLayer('top-right')"><i class="icon-nbd icon-nbd-fomat-top-left nbd-tooltip-hover" title="Top right"></i></li>
                    <li ng-click="translateLayer('horizontal')"><i class="icon-nbd icon-nbd-fomat-vertical-align-center nbd-tooltip-hover rotate90" title="<?php echo __('Center vertical'); ?>"></i></li>
                    <li ng-click="translateLayer('middle-left')"><i class="icon-nbd icon-nbd-fomat-top-left nbd-tooltip-hover rotate-135" title="<?php echo __('Middle left'); ?>"></i></li>
                    <li ng-click="translateLayer('center')"><i class="icon-nbd icon-nbd-bottom-center nbd-tooltip-hover middle-center" title="<?php echo __('Middle center'); ?>"></i></li>
                    <li ng-click="translateLayer('middle-right')"><i class="icon-nbd icon-nbd-fomat-top-left nbd-tooltip-hover rotate45" title="<?php echo __('Middle right'); ?>"></i></li>
                    <li style="opacity: 0;visibility: hidden"><i class="icon-nbd icon-nbd-info-circle nbd-tooltip-hover" title="<?php echo __('Intro'); ?>"></i></li>
                    <li ng-click="translateLayer('bottom-left')"><i class="icon-nbd icon-nbd-fomat-top-left nbd-tooltip-hover rotate-180" title="<?php echo __('Bottom left'); ?>"></i></li>
                    <li ng-click="translateLayer('bottom-center')"><i class="icon-nbd icon-nbd-fomat-top-left nbd-tooltip-hover rotate135" title="<?php echo __('Bottom center'); ?>"></i></li>
                    <li ng-click="translateLayer('bottom-right')"><i class="icon-nbd icon-nbd-fomat-top-left nbd-tooltip-hover rotate90" title="<?php echo __('Bottom right'); ?>"></i></li>
                </ul>
            </div>
        </li>
    </ul>
</div>