<div id="tab-element" class="v-tab-content v-more-toolbar" nbd-scroll="scrollLoadMore(container, type)"
     data-container="#tab-element" data-type="element" data-offset="20">
    <span class="v-title"><?php echo __('More'); ?></span>
    <div class="nbd-search v-action">
        <input ng-class="(resource.element.type != 'icon' || !resource.element.onclick) ? 'nbd-disabled' : ''"
               ng-keyup="$event.keyCode == 13 && getMedia(resource.element.type, 'search')" type="search" name="search"
               placeholder="<?php echo __('Search cliparts'); ?>" ng-model="resource.element.contentSearch"/>
        <i class="nbd-icon-vista nbd-icon-vista-search" ng-click="getMedia(resource.element.type, 'search')"></i>
    </div>
    <div class="v-content">
        <div class="tab-scroll">
            <div class="main-scrollbar">
                <div class="v-elements">
                    <div class="main-items">
                        <div class="items">
                            <div class="item"
                                 data-type="draw"
                                 data-api="false"
                                 ng-click="onClickTab('draw', 'element')"
                                 ng-if="settings['nbdesigner_enable_draw'] == 'yes' && !settings.is_mobile">
                                <div class="item-icon"><i class="nbd-icon-vista nbd-icon-vista-drawing"></i></div>
                                <div class="item-info">
                                    <span class="item-name" title="Draw"><?php echo __('Draw'); ?></span>
                                </div>
                            </div>
                            <div ng-if="settings['nbdesigner_enable_clipart'] == 'yes'" data-api="false" class="item"
                                 data-type="shapes" data-api="false" ng-click="onClickTab('shape', 'element')">
                                <div class="item-icon"><i class="nbd-icon-vista nbd-icon-vista-shapes"></i></div>
                                <div class="item-info">
                                    <span class="item-name" title="Shapes"><?php echo __('Shapes'); ?></span>
                                </div>
                            </div>
                            <div ng-if="settings['nbdesigner_enable_clipart'] == 'yes'" data-api="false"
                                 ng-click="onClickTab('icon', 'element')" class="item" data-type="icons"
                                 data-api="false">
                                <div class="item-icon"><i class="nbd-icon-vista nbd-icon-vista-diamond"></i></div>
                                <div class="item-info">
                                    <span class="item-name" title="Icons"><?php echo __('Icons'); ?></span>
                                </div>
                            </div>
                            <div ng-if="settings['nbdesigner_enable_qrcode'] == 'yes'" class="item" data-type="qr-code"
                                 data-api="false" ng-click="onClickTab('qrcode', 'element')">
                                <div class="item-icon"><i class="nbd-icon-vista nbd-icon-vista-qrcode"></i></div>
                                <div class="item-info">
                                    <span class="item-name" title="QR Code"><?php echo __('QR Code'); ?></span>
                                </div>
                            </div>
                            <div ng-if="settings['nbdesigner_enable_vcard'] == 'yes'"
                                 class="item" data-type="vcard" data-api="false"
                                 ng-click="onClickTab('vcard', 'element')">
                                <div class="main-item">
                                    <div class="item-icon">
                                        <i class="icon-vcard">
                                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                                 viewBox="0 0 32 32">
                                                <path fill="#06d79c"
                                                      d="M28 25h-3v-1c0.553 0 1-0.448 1-1 0-0.553-0.447-1-1-1h-2c-0.553 0-1 0.447-1 1 0 0.552 0.447 1 1 1v1h-13v-1c0.553 0 1-0.448 1-1 0-0.553-0.447-1-1-1h-2c-0.553 0-1 0.447-1 1 0 0.552 0.447 1 1 1v1h-4c-1.104 0-2-0.896-2-2v-14c0-1.104 0.896-2 2-2h24c1.104 0 2 0.896 2 2v14c0 1.104-0.896 2-2 2zM10 9.812c-1.208 0-2.188 1.287-2.188 2.875s0.98 2.875 2.188 2.875 2.188-1.287 2.188-2.875-0.98-2.875-2.188-2.875zM13.49 16.688c-0.539-0.359-2.091-0.598-2.091-0.598s-1.006 1.075-1.433 1.075c-0.428 0-1.434-1.075-1.434-1.075s-1.552 0.238-2.090 0.598c-0.539 0.358-0.777 2.261-0.777 2.261h8.615c0.001-0.001-0.157-1.84-0.79-2.261zM26 11h-9v1h9v-1zM26 13h-9v1h9v-1zM26 15h-9v1h9v-1zM26 17h-9v1h9v-1z"></path>
                                            </svg>
                                        </i>
                                    </div>
                                    <div class="item-info">
                                        <span class="item-name"><?php echo __('vCard'); ?></span>
                                    </div>
                                </div>
                            </div>
                            <div class="item" data-type="none"></div>
                        </div>
                        <div class="pointer"></div>
                    </div>
                    <div class="result-loaded">
                        <div class="content-items">
                            <div class="content-item type-draw" data-type="draw">
                                <div class="main-type">
                                    <span class="heading-title"><?php echo __('Free Drawing Mode'); ?></span>
                                    <div class="brush v-dropdown">
                                        <button class="v-btn v-btn-dropdown">
                                            <?php echo __('Brush'); ?>
                                            <i class="nbd-icon-vista nbd-icon-vista-arrow-drop-down v-dropdown-icon"></i>
                                        </button>
                                        <div class="v-dropdown-menu" data-pos="left">
                                            <ul class="tab-scroll">
                                                <li
                                                        ng-class="resource.drawMode.brushType == 'Pencil' ? 'active' : ''"
                                                        ng-click="resource.drawMode.brushType = 'Pencil';changeBush()">
                                                    <span><?php echo __('Pencil'); ?></span>
                                                </li>
                                                <li
                                                        ng-class="resource.drawMode.brushType == 'Circle' ? 'active' : ''"
                                                        ng-click="resource.drawMode.brushType = 'Circle';changeBush()">
                                                    <span><?php echo __('Circle'); ?></span>
                                                </li>
                                                <li
                                                        ng-class="resource.drawMode.brushType == 'Spray' ? 'active' : ''"
                                                        ng-click="resource.drawMode.brushType = 'Spray';changeBush()">
                                                    <span><?php echo __('Spray'); ?></span>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <ul class="v-ranges">
                                        <li class="range range-brightness">
                                            <label><?php echo __('Brush Width'); ?></label>
                                            <div class="main-track">
                                                <input class="slide-input" type="range" step="1" min="1" max="100"
                                                       value="50"
                                                       ng-model="resource.drawMode.brushWidth"
                                                       ng-change="changeBush()">
                                                <span class="range-track"></span>
                                            </div>
                                            <span class="value-display">{{resource.drawMode.brushWidth}}</span>
                                        </li>
                                    </ul>

                                    <div class="draw-color">
                                        <div class="nbd-color-palette show">
                                            <div class="nbd-color-palette-inner">
                                                <div class="working-palette"
                                                     ng-if="settings['nbdesigner_show_all_color'] == 'yes'">
                                                    <h3 class="color-palette-label"><?php echo __('Set color'); ?></h3>
                                                    <ul class="main-color-palette tab-scroll" style="max-height: 150px">
                                                        <li class="color-palette-add"
                                                            ng-init="showBrushColorPicker = false"
                                                            ng-click="showBrushColorPicker = !showBrushColorPicker;"
                                                            ng-style="{'background-color': currentColor}">
                                                        </li>
                                                        <li ng-repeat="color in listAddedColor track by $index"
                                                            class="color-palette-item" data-color="{color}"
                                                            ng-click="resource.drawMode.brushColor=color; changeBush()"
                                                            title="{{color}}"
                                                            ng-style="{'background-color': color}"></li>
                                                    </ul>
                                                </div>
                                                <div class="pinned-palette default-palette"
                                                     ng-if="settings['nbdesigner_show_all_color'] == 'yes'">
                                                    <h3 class="color-palette-label"><?php echo __('Default color'); ?></h3>
                                                    <ul class="main-color-palette"
                                                        ng-repeat="palette in resource.defaultPalette"
                                                        style="margin-bottom: 10px">
                                                        <li ng-class="{'first-left': $first, 'last-right': $last}"
                                                            ng-repeat="color in palette track by $index"
                                                            ng-click="resource.drawMode.brushColor=color; changeBush()"
                                                            class="color-palette-item"
                                                            data-color="{{color}}"
                                                            title="{{color}}"
                                                            ng-style="{'background': color}"></li>
                                                    </ul>
                                                </div>
                                                <div class="working-palette"
                                                     ng-if="settings['nbdesigner_show_all_color'] == 'no'">
                                                    <h3 class="color-palette-label"><?php echo __('Set color'); ?></h3>
                                                    <ul class="main-color-palette tab-scroll" style="max-height: 150px">
                                                        <li ng-repeat="color in __colorPalette track by $index"
                                                            class="color-palette-item" data-color="{color}"
                                                            ng-click="resource.drawMode.brushColor=color; changeBush()"
                                                            title="{{color}}"
                                                            ng-style="{'background-color': color}"></li>
                                                    </ul>
                                                </div>
                                                <div class="nbd-text-color-picker" id="nbd-text-color-picker"
                                                     style="z-index: 999;">
                                                    <spectrum-colorpicker
                                                            ng-model="currentColor"
                                                            options="{
                                                                preferredFormat: 'hex',
                                                                flat: true,
                                                                showButtons: false,
                                                                showInput: true,
                                                                containerClassName: 'nbd-sp'
                                                            }">
                                                    </spectrum-colorpicker>
                                                    <div>
                                                        <button class="v-btn"
                                                                ng-click="addColor();changeBush()"><?php echo __('Choose'); ?></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="content-item type-shapes" data-type="shapes" id="nbd-shape-wrap">
                                <div class="mansory-wrap">
                                    <div nbd-drag="art.url" extenal="true" type="svg" class="mansory-item"
                                         ng-click="addSvgFromMedia(art, $index)" ng-repeat="art in resource.shape.data"
                                         repeat-end="onEndRepeat('shape')"><img ng-src="{{art.url}}"><span
                                                class="photo-desc">{{art.name}}</span></div>
                                </div>
                            </div>
                            <div class="content-item type-icons" data-type="icons" id="nbd-icon-wrap">
                                <div class="mansory-wrap">
                                    <div nbd-drag="art.url" extenal="true" type="svg" class="mansory-item"
                                         ng-click="addSvgFromMedia(art, $index)" ng-repeat="art in resource.icon.data"
                                         repeat-end="onEndRepeat('icon')">
                                        <img ng-src="{{art.url}}"><span class="photo-desc">{{art.name}}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="content-item type-qrcode" data-type="qr-code">
                                <div class="main-type">
                                    <div class="main-input">
                                        <input ng-model="resource.qrText" type="text" class="nbd-input input-qrcode"
                                               name="qr-code" placeholder="https://yourcompany.com">
                                    </div>
                                    <button ng-class="resource.qrText != '' ? '' : 'nbd-disabled'" class="v-btn"
                                            ng-click="addQrCode()">
                                        <?php echo __('Create QRCode'); ?>
                                    </button>
                                    <div class="main-qrcode">

                                    </div>
                                </div>
                            </div>
                            <?php
                            $helper = $this->helper('Netbaseteam\Onlinedesign\Helper\Data');
                            $customerFirstName = $helper->getFirstNameCustomer();
                            $customerLastName = $helper->getLastNameCustomer();
                            $customerEmail = $helper->getEmailCustomer();
                            $customerAddress = $helper->getAddressCustomer();
                            $customerCity = $helper->getCityCustomer();
                            $customerPostCode = $helper->getPostCodeCustomer();
                            $customerCountry = $helper->getCountryCustomer();
                            $customerPhone = $helper->getTelePhoneCustomer();
                            $customerWebsite = $helper->getWebsiteCustomer();
                            ?>
                            <div ng-if="settings['nbdesigner_enable_vcard'] == 'yes'" class="content-item type-vcard"
                                 data-type="vcard">
                                <p class="nbd-vista-vcard-title"><?php echo __('Your information'); ?></p>
                                <div class=" md-input-wrap">
                                    <input placeholder="First Name" type="text" name="first_name" id="first_name"
                                           value="<?php echo $customerFirstName ? $customerFirstName : '' ?>">
                                </div>
                                <div class="md-input-wrap">
                                    <input placeholder="Last Name" type="text" name="last_name" id="last_name"
                                           value="<?php echo $customerLastName ? $customerLastName : '' ?>">
                                </div>
                                <div class=" md-input-wrap">
                                    <input placeholder="Address" type="text" name="address" id="address"
                                           value="<?php echo $customerAddress ? $customerAddress : '' ?>">
                                </div>
                                <div class=" md-input-wrap">
                                    <input placeholder="City" type="text" name="city" id="city"
                                           value="<?php echo $customerCity ? $customerCity : '' ?>">
                                </div>
                                <div class=" md-input-wrap">

                                    <input placeholder="Post Code" type="text" name="postcode" id="postcode"
                                           value="<?php echo $customerPostCode ? $customerPostCode : '' ?>">
                                </div>
                                <div class="md-input-wrap">
                                    <input placeholder="Country" type="text" name="country" id="country"
                                           value="<?php echo $customerCountry ? $customerCountry : '' ?>">
                                </div>
                                <div class=" md-input-wrap">
                                    <input placeholder="Phone" type="text" name="phone" id="phone"
                                           value="<?php echo $customerPhone ? $customerPhone : '' ?>">
                                </div>
                                <div class=" md-input-wrap">
                                    <input placeholder="Email" type="text" name="email" id="email"
                                           value="<?php echo $customerEmail ? $customerEmail : '' ?>">
                                </div>
                                <div class=" md-input-wrap">
                                    <input placeholder="Website" type="text" name="website" id="website"
                                           value="<?php echo $customerWebsite ? $customerWebsite : '' ?>">
                                </div>
                                <p>
    <span style="color: #fff;margin: 15px auto 0;width: 100%;" class="nbd-button" ng-click="generateVcard()"><?php echo __('Generate'); ?></span>
                                </p>
                            </div>
                        </div>
                        <div class="nbdesigner-gallery" id="nbdesigner-gallery"></div>
                    </div>
                    <div class="loading-photo" style="display: none; width: 40px; height: 40px;">
                        <svg class="circular" viewBox="25 25 50 50">
                            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2"
                                    stroke-miterlimit="10"/>
                        </svg>
                    </div>
                </div>
            </div>
        </div>
        <div class="info-support">
            <span><?php echo __('Facebook'); ?></span>
            <i class="nbd-icon-vista nbd-icon-vista-clear close-result-loaded" ng-click="onClickTab('', 'element')"></i>
        </div>
    </div>

</div>