<?php
$helper = $this->helper('Netbaseteam\Onlinedesign\Helper\Data');
$mapping = $helper->getTemplateMapping();
$config = $this->helper('Netbaseteam\Onlinedesign\Helper\Config');
include_once($helper->getLibOnlineDesign() . '/Onlinedesign/includes/mobiledetect.php');
include_once($helper->getLibOnlineDesign() . '/Onlinedesign/includes/class.helper.php');
include_once($helper->getLibOnlineDesign() . '/Onlinedesign/includes/class-util.php');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$admin_base_url = $objectManager->create('Magento\Backend\Helper\Data')->getAreaFrontName();
$default_font = nbd_get_default_font();
$_default_font = str_replace(" ", "+", json_decode($default_font)->alias);
$show_nbo_option = $helper->show_nbo_option();

$task2 = (isset($_GET['task2']) && $_GET['task2'] != '') ? $_GET['task2'] : '';
$task = (isset($_GET['task']) && $_GET['task'] != '') ? $_GET['task'] : 'new';
$order_id = (isset($_GET['orderid']) && $_GET['orderid'] != '') ? absint($_GET['orderid']) : '';
$product_id = (isset($_GET['product_id']) && $_GET['product_id'] != '') ? absint($_GET['product_id']) : '';
$variation_id = (isset($_GET['variation_id']) && $_GET['variation_id'] != '') ? absint($_GET['variation_id']) : 0;
$template_folder = (isset($_GET['template_folder']) && $_GET['template_folder'] != '') ? $_GET['template_folder'] : '';
$reference_product = (isset($_GET['reference_product']) && $_GET['reference_product'] != '') ? $_GET['reference_product'] : '';
$order_item_folder = (isset($_GET['order_item_folder']) && $_GET['order_item_folder'] != '') ? $_GET['order_item_folder'] : '';
$template_priority = (isset($_GET['priority']) && $_GET['priority'] != '') ? $_GET['priority'] : '';
$user_id = (get_current_user_id() > 0) ? get_current_user_id() : session_id();
$ui_mode = is_nbd_design_page() ? 2 : 1;/*1: iframe popup, 2: custom page, 3: studio*/
$valid_license = nbd_check_license() ? '1' : '0';

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->create('Magento\Catalog\Model\Product')->load($product_id);
?>

<!-- design template -->

<!DOCTYPE html>
<html lang="<?php echo get_bloginfo(); ?>">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>Online Designer</title>
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=1, minimum-scale=0.5, maximum-scale=1.0"/>
    <meta content="Online Designer - HTML5 Designer - Online Print Solution" name="description"/>
    <meta content="Online Designer" name="keywords"/>
    <meta content="Netbaseteam" name="author">
    <link type="text/css" href="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/css/jquery-ui.min.css'; ?>" rel="stylesheet"
          media="all"/>
    <link href='https://fonts.googleapis.com/css?family=<?php echo $_default_font; ?>:400,400i,700,700i'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Poppins:400,400i,700,700i' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,400i,700,700i' rel='stylesheet' type='text/css'>
    <link type="text/css" href="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/css/bootstrap.min.css'; ?>" rel="stylesheet"
          media="all"/>
    <link type="text/css" href="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/css/bundle.min.css'; ?>" rel="stylesheet"
          media="all"/>
    <link type="text/css" href="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/css/tooltipster.bundle.min.css'; ?>"
          rel="stylesheet" media="all"/>
    <link type="text/css" href="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/css/perfect-scrollbar.min.css'; ?>"
          rel="stylesheet" media="all"/>
    <link type="text/css" href="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/css/modern.min.css'; ?>" rel="stylesheet"
          media="all"/>
    <link type="text/css" href="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/css/spectrum.min.css'; ?>" rel="stylesheet"
          media="all">
    <link type="text/css" href="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/css/modern-additional.min.css?t=' . time(); ?>"
          rel="stylesheet" media="all"/>
    <link type="text/css" href="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/css/custom.min.css'; ?>" rel="stylesheet"
          media="all">

    <?php if ($show_nbo_option): ?>
        <link type="text/css" href="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/css/modern-print-option.min.css'; ?>"
              rel="stylesheet" media="all">
    <?php endif; ?>

    <?php if (is_rtl()): ?>
        <link type="text/css" href="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/css/modern-rtl.min.css'; ?>"
              rel="stylesheet" media="all"/>
    <?php endif; ?>
    <?php
    $enableColor = nbdesigner_get_option('nbdesigner_show_all_color');
    $enable_upload_multiple = nbdesigner_get_option('nbdesigner_upload_multiple_images');
    $design_type = (isset($_GET['design_type']) && $_GET['design_type'] != '') ? $_GET['design_type'] : '';
    $nbd_item_key = (isset($_GET['nbd_item_key']) && $_GET['nbd_item_key'] != '') ? $_GET['nbd_item_key'] : '';
    $nbu_item_key = (isset($_GET['nbu_item_key']) && $_GET['nbu_item_key'] != '') ? $_GET['nbu_item_key'] : '';
    $cart_item_key = (isset($_GET['cik']) && $_GET['cik'] != '') ? $_GET['cik'] : '';
    $reference = (isset($_GET['reference']) && $_GET['reference'] != '') ? $_GET['reference'] : '';
    $product_data = nbd_get_product_info($product_id, $variation_id, $nbd_item_key, $task, $task2,  $reference, false);
    $getParamNbdItemKey = $this->getRequest()->getParam('nbd_item_key');
    $getAdminCreateTemplates = $this->getRequest()->getParam('rd');
    if ($getAdminCreateTemplates == 'admin_templates') {
        $pid = $this->getRequest()->getParam('product_id');
        $key = $this->getRequest()->getParam('key');
        $urlAdminTemplates = $this->getUrl('admin/onlinedesign/index/edit/id/') . $pid . '/key/' . $key . '/';
    }
    $redirect_url = $getParamNbdItemKey && $getAdminCreateTemplates !='admin_templates' ? $this->getUrl('checkout/cart') : "";

    $_enable_upload = 0;
    $_enable_upload_without_design = 0;
    $enable_upload = $_enable_upload ? 2 : 1;
    $enable_upload_without_design = $_enable_upload_without_design ? 2 : 1;
    $home_url = $icl_home_url = $this->getUrl();
    $login_url = $this->getUrl('onlinedesign/myaccount/login');
    $cart_url = $this->getUrl('checkout/cart', ['_secure' => true]);
    $is_wpml = 0;
    $font_url = NBDESIGNER_FONT_URL;
    $fbID = nbdesigner_get_option('nbdesigner_facebook_app_id');
    $layout = 'modern';
    $templates = nbd_get_resource_templates($product_id, $variation_id, false);

    ?>

    <script type="text/javascript">
        var nbd_window = window.parent;
        var NBDESIGNCONFIG = {
            lang_code: "en_US",
            lang_rtl: "<?php if (is_rtl()) {
                echo 'rtl';
            } else {
                echo 'ltr';
            } ?>",
            is_mobile: "<?php echo wp_is_mobile(); ?>",
            ui_mode: "<?php echo $ui_mode; ?>",
            layout: "<?php echo $layout; ?>",
            show_nbo_option: "<?php echo $show_nbo_option; ?>",
            enable_upload: "<?php echo $enable_upload; ?>",
            enable_upload_without_design: "<?php echo $enable_upload_without_design; ?>",
            nbd_content_url: "<?php echo NBDESIGNER_DATA_URL ?>",
            font_url: "<?php echo $font_url; ?>",
            art_url: "<?php echo NBDESIGNER_ART_URL; ?>",
            admin_url_template: "<?php echo isset($urlAdminTemplates) ? $urlAdminTemplates : ''; ?>",
            assets_url: "<?php echo NBDESIGNER_PLUGIN_URL . 'assets/'; ?>",
            plg_url: "<?php echo NBDESIGNER_PLUGIN_URL; ?>",
            ajax_url: "<?php echo $this->getUrl('onlinedesign/index/info', array('_current' => true)); ?>",
            nonce: "<?php echo wp_create_nonce('save-design'); ?>",
            nonce_get: "<?php echo wp_create_nonce('nbdesigner-get-data'); ?>",
            instagram_redirect_uri: '',
            dropbox_redirect_uri: '',
            cart_url: "<?php echo $cart_url; ?>",
            task: "<?php echo $task; ?>",
            task2: "<?php echo $task2; ?>",
            design_type: "<?php echo $design_type; ?>",
            product_id: "<?php echo $product_id; ?>",
            variation_id: "<?php echo $variation_id; ?>",
            product_type: "<?php echo $product->getTypeId();?>",
            redirect_url: "<?php echo $redirect_url; ?>",
            checkout_url: "<?php echo $this->getUrl('checkout'); ?>",
            nbd_item_key: "<?php echo $nbd_item_key; ?>",
            nbu_item_key: "<?php echo $nbu_item_key; ?>",
            cart_item_key: "<?php echo $cart_item_key; ?>",
            home_url: "<?php echo $home_url; ?>",
            icl_home_url: "<?php echo $icl_home_url; ?>",
            is_logged:   <?php echo $helper->get_current_user_id() ? 'true' : 'false'; ?>,
            is_wpml:   <?php echo $is_wpml; ?>,
            enable_upload_multiple: "<?php echo $enable_upload_multiple; ?>",
            login_url: "<?php echo $login_url; ?>",
            product_data:   <?php echo json_encode($product_data); ?>,
            fonts: <?php echo nbd_get_fonts(); ?>,
            subsets: <?php echo json_encode(nbd_font_subsets()); ?>,
            fbID: "<?php echo $fbID; ?>",
            nbd_create_own_page: "<?php echo $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);?>",
            link_get_options: "<?php echo $this->getUrl('onlinedesign/index/quickview', array('id' => $product_id, 'quickview' => 1));?>",
            valid_license: "<?php echo $valid_license?>",
            enable_dropbox: false,
            default_font: <?php echo $default_font; ?>,
            templates: <?php echo json_encode($templates)?>,
            nbdlangs: {
                cliparts: "<?php echo __('Cliparts'); ?>",
                alert_upload_term: "<?php echo __('Please accept the upload term conditions'); ?>",
                path: "<?php echo __('Vector'); ?>",
                image: "<?php echo __('Image'); ?>",
                rect: "<?php echo __('Rectangle'); ?>",
                triangle: "<?php echo __('Triangle'); ?>",
                line: "<?php echo __('Line'); ?>",
                polygon: "<?php echo __('Polygon'); ?>",
                circle: "<?php echo __('Circle'); ?>",
                ellipse: "<?php echo __('Ellipse'); ?>",
                group: "<?php echo __('Group'); ?>",
                pro_license_alert: "<?php echo __('This item is not available in Lite version!'); ?>",
                confirm_delete_design: "<?php echo __('Do you want to delete this design?'); ?>",
                my_design: "<?php echo __('My design'); ?>",
                cover: "<?php echo __('Cover'); ?>",
                front_cover: "<?php echo __('Front cover'); ?>",
                back_cover: "<?php echo __('Back cover'); ?>",
                page: "<?php echo __('Page'); ?>",
                pages: "<?php echo __('Pages'); ?>",
                'image-layer': "<?php echo __('Group'); ?>",
                mask: "<?php echo __('Mask'); ?>"
            },
            listFontSizeInPt: ['6', '8', '10', '12', '14', '16', '18', '21', '24', '28', '32', '36', '42', '48', '56', '64', '72', '80', '88', '96', '104', '120', '144', '288', '576', '1152']
        };

        NBDESIGNCONFIG['default_variation_id'] = NBDESIGNCONFIG['variation_id'];
        <?php
        $settings = nbdesigner_get_all_frontend_setting();
        foreach ($settings as $key => $val):
        if(is_numeric($val)):
        ?>
        NBDESIGNCONFIG['<?php echo $key; ?>'] = <?php echo $val; ?>;
        <?php else: ?>
        NBDESIGNCONFIG['<?php echo $key; ?>'] = "<?php echo $val; ?>";
        <?php endif; ?>
        <?php endforeach; ?>
        <?php if( isset($product_data['option']['use_all_color']) ): ?>
        NBDESIGNCONFIG['nbdesigner_show_all_color'] = "<?php echo $product_data['option']['use_all_color'] == 1 ? 'yes' : 'no'; ?>";
        <?php endif; ?>
        <?php
        if( isset($product_data['option']['color_cats']) ):
        $cats = $product_data['option']['color_cats'];
        $colors = Nbdesigner_IO::read_json_setting(NBDESIGNER_DATA_DIR . '/colors.json');
        $colors = array_filter($colors, function ($val) use ($cats) {
            $check = false;
            if (sizeof($val->cat) == 0) {
                if (in_array('0', $cats)) $check = true;
            } else {
                $intercept = array_intersect($val->cat, $cats);
                if (count($intercept) == count($val->cat)) $check = true;
            }
            return $check;
        });
        $list_color = [];
        foreach ($colors as $color) {
            $list_color[] = $color->hex;
        }
        $list_color = array_unique($list_color);
        ?>
        var colorPalette = [], row = [], __colorPalette = [], color = '';
        <?php foreach($list_color as $cindex => $color): ?>
        color = "<?php echo $color; ?>";
        row.push(color);
        <?php if( $cindex % 10 == 9 ): ?>
        colorPalette.push(row);
        row = [];
        <?php endif; ?>
        __colorPalette.push(color);
        <?php endforeach; ?>
        <?php elseif( isset($product_data['option']['list_color']) ): ?>
        var colorPalette = [], row = [], __colorPalette = [], color = '';
        <?php foreach($product_data['option']['list_color'] as $cindex => $color): ?>
        color = "<?php echo $color['code']; ?>";
        row.push(color);
        <?php if( $cindex % 10 == 9 ): ?>
        colorPalette.push(row);
        row = [];
        <?php endif; ?>
        __colorPalette.push(color);
        <?php endforeach; ?>
        <?php else: ?>
        var _colors = NBDESIGNCONFIG['nbdesigner_hex_names'].split(','),
            colorPalette = [], row = [];
        __colorPalette = [];
        for (var i = 0; i < _colors.length; ++i) {
            var color = _colors[i].split(':')[0];
            row.push(color);
            if (i % 10 == 9) {
                colorPalette.push(row);
                row = [];
            }
            __colorPalette.push(color);
        }
        <?php endif; ?>
        row.push(NBDESIGNCONFIG['nbdesigner_default_color']);
        colorPalette.push(row);
        <?php if($ui_mode == 1): ?>
        nbd_window = window.parent;
        <?php else: ?>
        nbd_window = window;
        <?php endif; ?>
        <?php if( $layout == 'visual' ): ?>
        window.preventSubmitFormCart = true;
        <?php endif; ?>

    </script>
</head>

<body ng-app="nbd-app"
      class="nbd-mode-modern nbd-mode-<?php echo $ui_mode; ?> <?php echo (is_rtl()) ? 'nbd-modern-rtl' : ''; ?> ">
<div style="width: 100%; height: 100%;" ng-controller="designCtrl" ng-click="wraperClickHandle($event)" keypress
     class="ng-scope">
    <div id="design-container">
        <div class="container-fluid" id="designer-controller">
            <div class="nbd-navigations">
                <?php include 'modern/main-bar.phtml'; ?>
            </div>
            <div class="nbd-workspace">
                <?php include 'modern/sidebar.phtml'; ?>
                <div class="main <?php echo (wp_is_mobile()) ? 'active' : ''; ?>">
                    <?php include 'modern/toolbar.phtml';
                    include 'modern/stages.phtml';
                    include 'modern/toolbar-zoom.phtml';
                    include 'modern/warning.phtml';
                    include 'modern/context-menu.phtml';
                    include 'modern/loading-workflow.phtml';
                    if ($show_nbo_option && nbdesigner_get_option('nbdesigner_display_product_option') == '2' && !wp_is_mobile()) include 'modern/await-for-print-options.phtml';
                    ?>
                </div>
            </div>
        </div>
    </div>
    <?php
    include 'modern/popup.phtml';
    include 'modern/toasts.phtml';
    include 'modern/tip.phtml';
    include 'modern/color-palette.phtml';
    if (!wp_is_mobile()) include 'modern/tour-guide.phtml';
    ?>
</div>
<?php include 'modern/loading-page.phtml'; ?>

<script type='text/javascript' src="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/libs/jquery.min.js'; ?>"></script>
<script type='text/javascript' src="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/libs/jquery-ui.min.js'; ?>"></script>
<script type='text/javascript' src="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/libs/lodash.min.js'; ?>"></script>
<script type='text/javascript' src="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/libs/angular-1.6.9.min.js'; ?>"></script>
<script type="text/javascript" src="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/js/bundle-modern.min.js'; ?>"></script>
<script type="text/javascript" src="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/js/designer-modern.min.js'; ?>"></script>
<script type="text/javascript" src="<?php echo NBDESIGNER_PLUGIN_URL . 'assets/js/app-modern.min.js'; ?>"></script>
<?php if (file_exists(NBDESIGNER_DATA_DIR . '/custom.js')): ?>
    <script type="text/javascript" src="<?php echo NBDESIGNER_DATA_URL . '/custom.js'; ?>"></script>
<?php endif; ?>
</body>

</html>