<div class="nbd-context-menu" id="nbd-context-menu" style="display: none">
    <div class="main-context">
        <ul class="contexts">
            <li class="context-item"><i class="nbd-icon-vista nbd-icon-vista-reflect-horizontal"></i> <?php echo __('Reflect Horizontal'); ?></li>
            <li class="context-item"><i class="nbd-icon-vista nbd-icon-vista-reflect-vertical"></i> <?php echo __('Reflect Vertical'); ?></li>
            <li class="context-item"><i class="nbd-icon-vista nbd-icon-vista-replace-image"></i> <?php echo __('Replace Image'); ?></li>
            <li class="context-item"><i class="nbd-icon-vista nbd-icon-vista-vertical-align-center rotate90"></i> <?php echo __('Align Vertical Center'); ?></li>
            <li class="context-item"><i class="nbd-icon-vista nbd-icon-vista-vertical-align-center"></i> <?php echo __('Align Horizontal Center'); ?></li>
            <li class="context-item"><i class="nbd-icon-vista nbd-icon-vista-vertical-align-top rotate-90"></i> <?php echo __('Align Left'); ?></li>
            <li class="context-item"><i class="nbd-icon-vista nbd-icon-vista-vertical-align-top rotate90"></i> <?php echo __('Align Right'); ?></li>
            <li class="context-item"><i class="nbd-icon-vista nbd-icon-vista-vertical-align-top"></i> <?php echo __('Align Top'); ?></li>
            <li class="context-item"><i class="nbd-icon-vista nbd-icon-vista-vertical-align-top rotate-180"></i> <?php echo __('Align Bottom'); ?></li>
            <li class="context-item"><i class="nbd-icon-vista nbd-icon-vista-dis-horizontal"></i> <?php echo __('Distribute Horizontal'); ?></li>
            <li class="context-item"><i class="nbd-icon-vista nbd-icon-vista-dis-vertical"></i> <?php echo __('Distribute Vertical'); ?></li>
            <li class="separator"></li>
            <li class="context-item"><i class="nbd-icon-vista nbd-icon-vista-copy"></i> <?php echo __('Duplicate'); ?></li>
            <li class="context-item"><i class="nbd-icon-vista nbd-icon-vista-ungroup"></i> <?php echo __('Ungroup'); ?></li>
            <li class="context-item"><i class="nbd-icon-vista nbd-icon-vista-delete"></i> <?php echo __('Delete'); ?></li>
        </ul>
    </div>
</div>