<div class="v-popup" data-animate="scale">
    <div class="overlay-popup"></div>
    <div class="main-popup">
        <i class="nbd-icon-vista nbd-icon-vista-clear close-popup"></i>
        <div class="head">
        </div>
        <div class="body"></div>
        <div class="footer">
            <div class="nbd-list-button">
                <button class="nbd-button"><?php echo __('Pause'); ?></button>
                <button class="nbd-button"><?php echo __('Stop Webcam'); ?></button>
                <button class="nbd-button"><?php echo __('Capture'); ?></button>
            </div>
        </div>
    </div>
</div>

<div class="v-popup v-popup-terms" data-animate="fixed-top">
    <div class="overlay-popup"></div>
    <div class="main-popup">
        <i class="nbd-icon-vista nbd-icon-vista-clear close-popup"></i>
        <div class="head">Image upload terms</div>
        <div class="body">
            {{settings['nbdesigner_upload_term']}}
        </div>
        <div class="footer"></div>
    </div>
</div>

<div class="v-popup v-popup-webcam" data-animate="scale">
    <div class="overlay-popup"></div>
    <div class="main-popup">
        <i class="nbd-icon-vista nbd-icon-vista-clear close-popup"></i>
        <div class="head">
        </div>
        <div class="body"></div>
        <div class="footer">
            <div class="nbd-list-button">
                <button class="v-btn"><?php echo __('Pause'); ?></button>
                <button class="v-btn">Stop <?php echo __('Webcam'); ?></button>
                <button class="v-btn"><?php echo __('Capture'); ?></button>
            </div>
        </div>
    </div>
</div>

<div class="v-popup v-popup-select clear-stage-alert" data-animate="scale">
    <div class="overlay-popup"></div>
    <div class="main-popup">
        <i class="nbd-icon-vista nbd-icon-vista-clear close-popup"></i>
        <div class="head">
            <?php echo  __('Delete All Layers'); ?>
        </div>
        <div class="body">
            <div class="main-body">
                <span class="title"><?php echo __('Are you sure you want to delete all layers?'); ?></span>
                <div class="main-select">
                    <button ng-click="closePopupClearStage()" class="v-btn select-no"><i class="nbd-icon-vista nbd-icon-vista-clear"></i> <?php echo __('No'); ?></button>
                    <button ng-click="clearStage()" class="v-btn select-yes"><i class="nbd-icon-vista nbd-icon-vista-done"></i> <?php echo __('Yes'); ?></button>
                </div>
            </div>
        </div>
        <div class="footer"></div>
    </div>
</div>