<?php
/* add js for */
echo $this->getLayout()->createBlock('Netbaseteam\Onlinedesign\Block\Onlinedesign')
->setTemplate('Netbaseteam_Onlinedesign::nbdesigner.phtml')->toHtml();
?>
<?php
$helper = $this->helper('Netbaseteam\Onlinedesign\Helper\Data');
$product_id = $block->getCurrentProduct()->getId();
$visuaLayout = $helper->getDesignLayout($product_id);
if($visuaLayout == 1) {
include_once($helper->getLibOnlineDesign() . '/Onlinedesign/includes/class.helper.php');
include_once($helper->getLibOnlineDesign() . '/Onlinedesign/includes/class-util.php');
$login_url = $this->getUrl('onlinedesign/myaccount/login');
$default_font = nbd_get_default_font();
$enableColor = nbdesigner_get_option('nbdesigner_show_all_color');
$enable_upload_multiple = nbdesigner_get_option('nbdesigner_upload_multiple_images');
$task = (isset($_GET['task']) && $_GET['task'] != '') ? $_GET['task'] : 'new';
$task2 = (isset($_GET['task2']) && $_GET['task2'] != '') ? $_GET['task2'] : '';
$design_type = (isset($_GET['design_type']) && $_GET['design_type'] != '') ? $_GET['design_type'] : '';
$nbd_item_key = (isset($_GET['nbd_item_key']) && $_GET['nbd_item_key'] != '') ? $_GET['nbd_item_key'] : '';
$nbu_item_key = (isset($_GET['nbu_item_key']) && $_GET['nbu_item_key'] != '') ? $_GET['nbu_item_key'] : '';
$cart_item_key = (isset($_GET['cik']) && $_GET['cik'] != '') ? $_GET['cik'] : '';
$reference = (isset($_GET['reference']) && $_GET['reference'] != '') ? $_GET['reference'] : '';
$ui_mode = 3;/*1: Iframe popup, 2: Editor page, 3: Div in detail product*/
$redirect_url = (isset($_GET['rd']) && $_GET['rd'] != '') ? nbd_get_redirect_url() : (($task == 'new' && $ui_mode == 2) ? wc_get_cart_url() : '');
//$redirect_url = (isset($_GET['rd']) &&  $_GET['rd'] != '') ? $_GET['rd'] : (($task == 'new' && $ui_mode == 2) ? wc_get_cart_url() : '');
$_enable_upload = get_post_meta($product_id, '_nbdesigner_enable_upload', true);
$_enable_upload_without_design = get_post_meta($product_id, '_nbdesigner_enable_upload_without_design', true);
$enable_upload = $_enable_upload ? 2 : 1;
$enable_upload_without_design = $_enable_upload_without_design ? 2 : 1;
$variation_id = 0;
$show_nbo_option = false;
$home_url = $icl_home_url = $this->getUrl();
$is_wpml = 0;
$font_url = NBDESIGNER_FONT_URL;
$fbID = nbdesigner_get_option('nbdesigner_facebook_app_id');
$dbID = nbdesigner_get_option('nbdesigner_dropbox_app_id');
$ingId = nbdesigner_get_option('nbdesigner_instagram_app_id');
$layout = 'visual';
$product_data = nbd_get_product_info($product_id, $variation_id, $nbd_item_key, $task, $task2, $reference, false, $cart_item_key);
$link_get_options = '';
$templates = nbd_get_resource_templates($product_id, $variation_id, 100);
$valid_license = nbd_check_license();
    $visuaDesignUrl = $this->getUrl('onlinedesign/index/design', array('_current' => true));
    $visuaDesignUrl .= "?product_id=" . $product_id;

?>
<script type="text/javascript">
    var nbd_window = window.parent;
    var NBDESIGNCONFIG = {
        lang_code: "en_US",
        lang_rtl: "<?php if (is_rtl()) {
            echo 'rtl';
        } else {
            echo 'ltr';
        } ?>",
        is_mobile: "<?php echo wp_is_mobile(); ?>",
        ui_mode: "<?php echo $ui_mode; ?>",
        layout: "<?php echo $layout; ?>",
        show_nbo_option: "<?php echo $show_nbo_option; ?>",
        enable_upload: "<?php echo $enable_upload; ?>",
        design_url_visual: "<?php $visuaDesignUrl ?>",
        enable_upload_without_design: "<?php echo $enable_upload_without_design; ?>",
        nbd_content_url: "<?php echo NBDESIGNER_DATA_URL ?>",
        font_url: "<?php echo $font_url; ?>",
        art_url: "<?php echo NBDESIGNER_ART_URL; ?>",
        assets_url: "<?php echo NBDESIGNER_PLUGIN_URL . 'assets/'; ?>",
        plg_url: "<?php echo NBDESIGNER_PLUGIN_URL; ?>",
        base_url: "<?php echo $this->getBaseUrl() ?>",
        ajax_url: "<?php echo $this->getUrl('onlinedesign/index/info', array('_current' => true)); ?>",
        nonce: "<?php echo wp_create_nonce('save-design'); ?>",
        nonce_get: "<?php echo wp_create_nonce('nbdesigner-get-data'); ?>",
        instagram_redirect_uri: '',
        dropbox_redirect_uri: '',
        cart_url: '',
        task: "<?php echo $task; ?>",
        task2: "<?php echo $task2; ?>",
        design_type: "<?php echo $design_type; ?>",
        product_id: "<?php echo $product_id; ?>",
        variation_id: "<?php echo $product_id; ?>",
        product_type: '',
        redirect_url: "<?php echo $redirect_url; ?>",
        nbd_item_key: "<?php echo $nbd_item_key; ?>",
        nbu_item_key: "<?php echo $nbu_item_key; ?>",
        cart_item_key: "<?php echo $cart_item_key; ?>",
        home_url: "<?php echo $home_url; ?>",
        icl_home_url: "<?php echo $icl_home_url; ?>",
        is_logged:   <?php echo $helper->get_current_user_id() ? 'true' : 'false'; ?>,
        is_wpml:   <?php echo $is_wpml; ?>,
        enable_upload_multiple: "<?php echo $enable_upload_multiple; ?>",
        login_url: "<?php echo $login_url; ?>",
        product_data:   <?php echo json_encode($product_data); ?>,
        fonts: <?php echo nbd_get_fonts(); ?>,
        subsets: <?php echo json_encode(nbd_font_subsets()); ?>,
        fbID: "<?php echo $fbID; ?>",
        nbd_create_own_page: "<?php echo $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);?>",
        link_get_options: '',
        valid_license: "<?php echo $valid_license?>",
        enable_dropbox: false,
        default_font: <?php echo $default_font; ?>,
        templates: <?php echo json_encode($templates)?>,
        nbdlangs: {
            cliparts: "<?php echo __('Cliparts'); ?>",
            alert_upload_term: "<?php echo __('Please accept the upload term conditions'); ?>",
            path: "<?php echo __('Vector'); ?>",
            image: "<?php echo __('Image'); ?>",
            rect: "<?php echo __('Rectangle'); ?>",
            triangle: "<?php echo __('Triangle'); ?>",
            line: "<?php echo __('Line'); ?>",
            polygon: "<?php echo __('Polygon'); ?>",
            circle: "<?php echo __('Circle'); ?>",
            ellipse: "<?php echo __('Ellipse'); ?>",
            group: "<?php echo __('Group'); ?>",
            pro_license_alert: "<?php echo __('This item is not available in Lite version!'); ?>",
            confirm_delete_design: "<?php echo __('Do you want to delete this design?'); ?>",
            my_design: "<?php echo __('My design'); ?>"
        },
        listFontSizeInPt: ['6', '8', '10', '12', '14', '16', '18', '21', '24', '28', '32', '36', '42', '48', '56', '64', '72', '80', '88', '96', '104', '120', '144', '288', '576', '1152']
    };

    NBDESIGNCONFIG['default_variation_id'] = NBDESIGNCONFIG['variation_id'];
    <?php
    $settings = nbdesigner_get_all_frontend_setting();
    foreach ($settings as $key => $val):
    if(is_numeric($val)):
    ?>
    NBDESIGNCONFIG['<?php echo $key; ?>'] = <?php echo $val; ?>;
    <?php else: ?>
    NBDESIGNCONFIG['<?php echo $key; ?>'] = "<?php echo $val; ?>";
    <?php endif; ?>
    <?php endforeach; ?>
    <?php if( isset($product_data['option']['use_all_color']) ): ?>
    NBDESIGNCONFIG['nbdesigner_show_all_color'] = "<?php echo $product_data['option']['use_all_color'] == 1 ? 'yes' : 'no'; ?>";
    <?php endif; ?>
    <?php
    if( isset($product_data['option']['color_cats']) ):
    $cats = $product_data['option']['color_cats'];
    $colors = Nbdesigner_IO::read_json_setting(NBDESIGNER_DATA_DIR . '/colors.json');
    $colors = array_filter($colors, function ($val) use ($cats) {
        $check = false;
        if (sizeof($val->cat) == 0) {
            if (in_array('0', $cats)) $check = true;
        } else {
            $intercept = array_intersect($val->cat, $cats);
            if (count($intercept) == count($val->cat)) $check = true;
        }
        return $check;
    });
    $list_color = [];
    foreach ($colors as $color) {
        $list_color[] = $color->hex;
    }
    $list_color = array_unique($list_color);
    ?>
    var colorPalette = [], row = [], __colorPalette = [], color = '';
    <?php foreach($list_color as $cindex => $color): ?>
    color = "<?php echo $color; ?>";
    row.push(color);
    <?php if( $cindex % 10 == 9 ): ?>
    colorPalette.push(row);
    row = [];
    <?php endif; ?>
    __colorPalette.push(color);
    <?php endforeach; ?>
    <?php elseif( isset($product_data['option']['list_color']) ): ?>
    var colorPalette = [], row = [], __colorPalette = [], color = '';
    <?php foreach($product_data['option']['list_color'] as $cindex => $color): ?>
    color = "<?php echo $color['code']; ?>";
    row.push(color);
    <?php if( $cindex % 10 == 9 ): ?>
    colorPalette.push(row);
    row = [];
    <?php endif; ?>
    __colorPalette.push(color);
    <?php endforeach; ?>
    <?php else: ?>
    var _colors = NBDESIGNCONFIG['nbdesigner_hex_names'].split(','),
        colorPalette = [], row = [];
    __colorPalette = [];
    for (var i = 0; i < _colors.length; ++i) {
        var color = _colors[i].split(':')[0];
        row.push(color);
        if (i % 10 == 9) {
            colorPalette.push(row);
            row = [];
        }
        __colorPalette.push(color);
    }
    <?php endif; ?>
    row.push(NBDESIGNCONFIG['nbdesigner_default_color']);
    colorPalette.push(row);
    <?php if($ui_mode == 1): ?>
    nbd_window = window.parent;
    <?php else: ?>
    nbd_window = window;
    <?php endif; ?>
    <?php if( $layout == 'visual' ): ?>
    window.preventSubmitFormCart = true;
    <?php endif; ?>

</script>
<style>
    .nbd-mode-vista .nbd-stages .page-toolbar .page-main ul li i.nbd-icon-vista-arrow-upward {
        background: #ddd;
        border-radius: 12px;
        padding: 8px 0;
    }
    @media (min-width: 768px), print {
        .page-layout-1column .product.media {
            width: 25%;
        }
        .page-layout-1column .product-info-main {
            width: 70%;
        }
    }
    .bundle-options-container .block-bundle-summary .box-tocart, .box-tocart {
        width: 50%;
    }
    .nbd-mode-vista .v-toolbox .v-toolbox-item {
        max-width: 320px;
    }

    @media (min-width: 768px) {
        .nbd-visual-layout .entry-summary {
            width: 100% !important;
        }

        .nbd-visual-layout .nbo-fields-wrapper {
            width: 50% !important;
            float: left !important;
            padding-right: 1.1em;
        }

        .nbd-visual-layout .nbo-summary-wrapper {
            width: 50% !important;
            float: left !important;
        }
    }

    .nbd-designer #primary, .nbd-designer.woocommerce div.product {
        overflow: unset !important;
    }

    .nbd-on-task:after {
        content: "";
        position: fixed;
        top: 0px;
        left: 0px;
        background: #fff;
        opacity: 1;
        width: 100vw;
        height: 100vh;
        z-index: 10000001;
        transition: opacity 250ms ease;
        cursor: default;
    }

    .nbd-on-task .nbd-vista-ctrl {
        position: relative;
        z-index: 10000002;
    }

    .nbd-mode-vista .v-toolbox .v-toolbox-item {
        top: 100%;
        left: 50%;
        transform: translateX(-100%);
        -webkit-transition: all 0.3s;
        -moz-transition: all 0.3s;
        transition: all 0.3s;
    }

    .nbd-mode-vista .v-sidebar .v-content .text-editor.active .text-field {
        background: #888;
        color: #fff;
        -webkit-transition: all 0.4s;
        -moz-transition: all 0.4s;
        transition: all 0.4s;
    }

    .nbd-mode-vista .nbd-stages .stages-inner .stage .stage-main .design-wrap {
        overflow: hidden;
    }

    .nbd-mode-vista .nbd-stages .stages-inner .stage .stage-main .design-wrap .bounding-layers .bounding-layers-inner .layer-angle span {
        font-size: 10px;
    }

    .nbd-mode-vista .v-toolbox .v-toolbox-text .toolbar-font-search input {
        border: 1px solid #ebebeb !important;
    }

    .v-content.nbd-tab-contents:after,
    #tab-text.nbd-tab-contents:after,
    #tab-photo .v-content:after,
    #tab-element .v-content:after {
        content: '';
        position: absolute;
        bottom: -30px;
        width: 100%;
        height: 30px;
        pointer-events: none;
        box-shadow: 0px 1px 0px rgba(255, 255, 255, 0.8) inset, 0px -15px 15px rgba(255, 255, 255, 0.6);
    }

    @media screen and (max-width: 768px) {
        .nbd-mode-vista .v-workspace {
            width: 100%;
        }

        .nbd-mode-vista .v-layout {
            width: 100% !important;
        }

        .v-workspace {
            flex-wrap: wrap;
        }

        .toolbar-input {
            font-size: 16px !important;
        }

        .nbd-mode-vista .v-sidebar .v-content .text-editor .text-field {
            font-size: 16px;
        }

        .nbd-mode-vista.nbd-mobile .v-toolbar .main-toolbar .v-toolbar-item:after {
            display: block;
            position: absolute;
            top: 0;
            right: 0;
            height: 100%;
            content: '';
            width: 60px;
            background-color: transparent;
            background-image: linear-gradient(to right, rgba(255, 255, 255, 0), rgba(255, 255, 255, 0.55));
            pointer-events: none;
        }
    }
</style>

<?php $mode3Task = (isset($_GET['nbdv-task']) && $_GET['nbdv-task'] != '') ? $_GET['nbdv-task'] : ''; ?>
<div id="nbd-vista-app"
     class="nbd-mode-vista <?php echo wp_is_mobile() ? 'nbd-mobile' : 'nbd-desktop'; ?> <?php echo (is_rtl()) ? 'nbd-rtl' : '' ?> <?php if (isset($_GET['nbdv-task']) && $_GET['nbdv-task'] != '') echo '1nbd-on-task'; ?>">
    <div class="nbd-vista-ctrl" ng-controller="designCtrl" keypress ng-cloak>
        <div id="design-container">
            <div class="container-fluid" id="designer-controller">
                <div class="nbd-vista">
                    <div class="main-vista">
                        <?php include "toolbar.phtml"; ?>
                        <div class="v-workspace">
                            <?php include "sidebar.phtml"; ?>
                            <?php include "layout.phtml"; ?>
                            <?php include "warning.phtml"; ?>
                            <?php include "toasts.phtml"; ?>
                        </div>
                    </div>
                    <?php include 'popup.phtml'; ?>
                    <?php include 'context-menu.phtml'; ?>
                    <?php include 'loading-app.phtml'; ?>
                </div>

                <?php include 'save-template.phtml'; ?>
            </div>
        </div>
    </div>
</div>

<?php } ?>