<strong>Notice</strong><br /><br />
After change bellow <span style="background: #dddacd; font-weight: bold;">values</span>, <span style="background: #f0c6f6; font-weight: bold;">relative position</span> of design area in bounding box will automatic update.<br /><br />
Notice: W<span>p</span> &gt;= W<span>d</span> + L<span>d</span> | H<span>p</span> &gt;= H<span>d</span> + T<span>d</span><br>If color labels change to <span style="color: red">red</span>, check values again.<br /><br />
There <span style="background: #dddacd; font-weight: bold;">values</span> will decide dimensions of output images.<br /><br />
If you modify <span style="background: #f0c6f6; font-weight: bold;">relative position</span>, click button <strong>[ Update Area Size ]</strong> to update<span style="background: #dddacd; font-weight: bold;"> design area.</span><br /><br />
