<!DOCTYPE html>
<html>
<head>
<style>
/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content-popup {
    background-color: #fefefe;
    margin: auto;
    padding: 20px;
    border: 1px solid #888;
    width: 50%;
}

/* The Close Button */
.close {
    color: #aaaaaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
}
</style>
</head>
<body>

<!-- <h2>Modal Example</h2> -->

<!-- Trigger/Open The Modal -->
<!-- <button id="myBtn">Open Modal</button> -->

<!-- The Modal -->
<div id="myModal" class="modal">

	<!-- Modal content -->
	<div id="content-modal" class="modal-content">
		<span id="close-modal-faceapi" class="close">&times;</span>

		<div id="tab-panel-facebook" class="help-tab-content active" style="">
		   <h2>How to get Facebook API ID</h2>
		   <span style="color:#CB4B16;">Application</span> Key and Secret (also sometimes referred as <span style="color:#CB4B16;">Consumer</span> key and secret or <span style="color:#CB4B16;">Client</span> id and secret) are what we call an application credentials.This application will link your website <code>dev.cmsmart.net</code> to <code>Facebook API</code> and these credentials are needed in order for <b>NBDesigner</b> users to use they Facebook photos.<br>These credentials may also differ in format, name and content depending on the social network.<br><br>To enable authentication with this provider and to register a new <b>Facebook API Application</b>, follow the steps:<br>
		   <div style="margin-left:40px;">
			  <p><b>1. </b>First go to: <a href="https://developers.facebook.com/apps">https://developers.facebook.com/apps</a></p>
			  <p><b>2. </b>Select <b>Add a New App</b> from the <b>Apps</b> menu at the top</p>
			  <p><b>3. </b>Fill out Display Name, Namespace, choose a category and click <b>Create App</b></p>
			  <p><b>4. </b>Go to Settings page and click on <b>Add Platform</b>. Choose website and enter in the new screen your website url in <b>App Domains</b> and <b>Site URL</b> fieldsThey should match with the current hostname <em style="color:#CB4B16;">dev.cmsmart.net</em>.</p>
			  <p><b>5. </b>Go to the <b>App Review</b> page and choose <b>yes</b> where it says <b>Do you want to make this app and all its live features available to the general public?</b>In section "Submit Items for Approval" click <b>Start a Submission</b>, in popup check "user_photos" and complete all steps</p>
			  <p><b>6. </b>Go back to the <b>Dashboard</b> page and past the created application credentials (APP ID and Secret) into the boxes above</p>
		   </div>
		   <hr>
		   <div>
			  <p><b>And that's it! If for some reason you still can't manage to create an application for Facebook, first try to <a href="https://www.google.com/search?q=Facebook API create application" target="_blank">Google it</a>, then check it on <a href="http://www.youtube.com/results?search_query=Facebook API create application " target="_blank">Youtube</a>, and if nothing works <a href="https://cmsmart.net/support_ticket">ask for support</a></b></p>
		   </div>
		</div>
	</div>

</div>

<script>
	function open_help_faceapi() {
		require([
			'jquery'
		], function ($) {
			$('#content-modal').addClass("modal-content-popup");
			$('#myModal').css("display", "block");
			return;
		});
	}

	require([
		'jquery'
	], function ($) {
		$("#close-modal-faceapi").click(function() {
			$('#content-modal').removeClass("modal-content-popup");
			$('#myModal').css("display", "none");
			return;
		});
		
	});
</script>

</body>
</html>
