<strong>Notice</strong><br /><br />
Please upload background image with aspect ratio: Wp x Hp<br /><br />
Make sure setting <span style="font-weight: bold; background: #b8dce8;">Product size</span> must always be the top priority!<br /><br />
You have two order setting options: <br><strong>1</strong> - <span style="font-weight: bold; background: #b8dce8;">Product size</span> -> <span style="font-weight: bold; background: #dddacd;">Design area size</span>  (<span style="font-weight: bold; background: #f0c6f6;">Relative position</span> will automatic update)<br />
<strong>2</strong> - <span style="font-weight: bold; background: #b8dce8;">Product size</span> -> <span style="font-weight: bold; background: #f0c6f6;">Relative position</span> -> click <span class="dashicons dashicons-update">[ Update Area Size ]</span> to update <span style="font-weight: bold; background: #f0c6f6;">Design area size</span>
   