<strong>Notice</strong><br /><br />
Bellow values must in range from 0 to 500px<br />
There are relative position of design area in bounding box.<br /><br />
<img style="max-width: 100%;" src="<?php echo $this->getViewFileUrl('Netbaseteam_Onlinedesign::images/bounding-box.png') ?>"><br><a href="<?php echo $this->getViewFileUrl('Netbaseteam_Onlinedesign::images/bounding-box.png') ?>" target="_blank">See detail</a>