<div id="body-overlay-loader" style="display: none;"><div><img src="<?php echo $this->getViewFileUrl('Netbaseteam_Onlinedesign/images/loading.gif');?>" width="64px" height="64px"/></div></div>
<script>
    require([
        'jquery',
        'prototype',
    ], function($){
        function func_getkey() {
            var formData = new FormData();
            var form_key = FORM_KEY;
            var email = $('input#nb_onlinedesign_license_get_license_get_license_code_email').val();
            var username = $('input#nb_onlinedesign_license_get_license_get_license_code_user').val();
            formData.append('form_key', form_key);
            formData.append('get_license_email', email);
            formData.append('get_license_user', username);
            var validateEmail = isEmail(email);

            if (email == '') {
                alert('Please input a email!');
            } else if (!validateEmail) {
                alert('Email format is incorrect!');
            } else if (username == '') {
                alert('Please input a username!');
            } else {
                $.ajax({
                    url: '<?php echo $block->getAjaxUrl() ?>',
                    type: "POST",
                    data:  formData,
                    contentType: false,
                    processData: false,
                    cache: false,
                    beforeSend: function () {
                        $("#body-overlay-loader").show();
                    },
                    success: function()
                    {
                        $("#body-overlay-loader").hide();
                        alert('Send email success. Please check your email!');
                        $('.page-actions .page-actions-buttons>button.primary').click();
                    }
                });
            }

        }

        function isEmail(email) {
            var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            return regex.test(email);
        }

        $('#btn_getkey').click(function () {
            func_getkey();
        });
    });
</script>
<?php echo $block->getButtonHtml()?>