<div class="nbd-popup popup-select clear-stage-alert" data-animate="scale">
    <div class="main-popup">
        <i class="icon-nbd icon-nbd-clear close-popup"></i>
        <div class="head">
            <?php echo __('Delete All Layers'); ?>
        </div>
        <div class="body">
            <div class="main-body">
                <span class="title"><?php echo __('Are you sure you want to delete all layers?'); ?></span>
                <div class="main-select">
                    <button ng-click="closePopupClearStage()" class="nbd-button select-no"><i class="icon-nbd icon-nbd-clear"></i> <?php echo __('No'); ?></button>
                    <button ng-click="clearStage()" class="nbd-button select-yes"><i class="icon-nbd icon-nbd-fomat-done"></i> <?php echo __('Yes'); ?></button>
                </div>
            </div>
        </div>
        <div class="footer"></div>
    </div>
</div>