<div class="nbd-popup popup-nbd-bleedline-popup" data-animate="scale">
    <div class="main-popup" style="padding: 0;">
        <i class="icon-nbd icon-nbd-clear close-popup"></i>
        <div class="head">
            <h2 style="font-size: 18px;margin: 0;padding: 20px;font-weight: bold;text-transform: uppercase; border-bottom: 1px solid #ddd;"><?php echo __('Guidelines'); ?></h2>
        </div>
        <div class="body" style="padding: 20px;">
            <div class="main-body">
                <p class="bleed-note"><?php echo __('Bleed Line'); ?></p>
                <p><?php echo __('This is where we aim to trim the product. The actual line can vary due to the trimming process.'); ?></p>
                <p class="safezone-note"><?php echo __('Safe zone'); ?></p>
                <p><?php echo __('Keep text and important imagery within this line to ensure it does not get cut off during trimming. '); ?></p>
            </div>
        </div>
        <div class="footer"></div>
    </div>
</div>

