<div class="nbd-sidebar-preview product-more-info">
    <div class="preview-head">
        <span><?php echo __('infomation'); ?></span>
        <i class="icon-nbd icon-nbd-fomat-highlight-off close-preview"></i>
    </div>
    <div class="main-preview tab-scroll">
        <div class="preview-body">
        </div>
        <div class="preview-footer">
            <div class="main-footer">
                <button class="nbd-button"><?php echo __('Choose'); ?></button>
            </div>
        </div>
    </div>
</div>