<div class="tabs-content">
    <i class="fa fa-times" aria-hidden="true"></i>
    <span class="hide-tablet"><i class="icon-nbd icon-nbd-fomat-top-left rotate-135"></i></span>
    <?php if( $show_nbo_option && $settings['nbdesigner_display_product_option'] == '2' && !wp_is_mobile() ): ?>
    <?php include 'tab-product.phtml'; ?>
    <?php endif; ?>
    <?php if( isset($product_data["option"]['admindesign']) && $product_data["option"]['admindesign'] != "0" ): ?>
    <?php include 'tab-templates.phtml'; ?>
    <?php endif; ?>
    <?php include 'tab-typography.phtml'; ?>
    <?php include 'tab-clipart.phtml'; ?>    
    <?php include 'tab-photo.phtml'; ?> 
    <?php if($show_elements_tab) include 'tab-elements.phtml'; ?>
    <?php if($settings["nbdesigner_hide_layer_tab"] == "no") include 'tab-layer.phtml'; ?>
</div>