<div class="nbd-toolbar animated" ng-class="stages[currentStage].states.isActiveLayer ? 'fadeInDown' : 'fadeOutUp'">
    <div class="main-toolbar">
        <?php include 'toolbars/toolbar-text.phtml'; ?>
        <?php include 'toolbars/toolbar-image.phtml'; ?>
        <?php include 'toolbars/toolbar-group.phtml'; ?>
        <?php include 'toolbars/toolbar-path.phtml';?>
        <?php include 'toolbars/toolbar-common.phtml'; ?>
        <?php include 'toolbars/color-palette.phtml';?>
    </div>
</div>